package vista;

import entidades.Categoria;
import entidades.CategoriaData;
import entidades.Producto;
import entidades.ProductoData;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author FEDE-PC
 */
public class Escritorio extends javax.swing.JFrame {

    private CategoriaData cd;
    private ProductoData pd;
    private DefaultTableModel modelo;
    private Producto productoElegido;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Escritorio.class.getName());

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
        pd = new ProductoData();
        cd = new CategoriaData();
        modelo = new DefaultTableModel();
        llenarCM();
        desactivarCampos();
        llenarCabezera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        JIFGestionDeProductos = new javax.swing.JInternalFrame();
        lblGestionDeProductosTitulo = new javax.swing.JLabel();
        lblGestionDeProductosFiltrar = new javax.swing.JLabel();
        cmbFiltrarPorCategoria = new javax.swing.JComboBox<>();
        scpGestionDeProductos = new javax.swing.JScrollPane();
        tblGestionDeProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblGestionDeProductosCodigo = new javax.swing.JLabel();
        lblGestionDeProductosDescipcion = new javax.swing.JLabel();
        lblGestionDeProductosPrecio = new javax.swing.JLabel();
        lblGestionDeProductosRubro = new javax.swing.JLabel();
        lblGestionDeProductosStock = new javax.swing.JLabel();
        txtGestionDeProductosCodigo = new javax.swing.JTextField();
        txtGestionDeProductosDescripcion = new javax.swing.JTextField();
        txtGestionDeProductosPrecio = new javax.swing.JTextField();
        cmbGestionDeProductosCombo = new javax.swing.JComboBox<>();
        spnGestionDeProductos = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        JIFListadoPorNombre = new javax.swing.JInternalFrame();
        lblListadoPorNombreTitulo = new javax.swing.JLabel();
        lblListadoPorNombreIngDescripcion = new javax.swing.JLabel();
        scpListadoPorNombre = new javax.swing.JScrollPane();
        tblListadoPorNombre = new javax.swing.JTable();
        txtListadoPorNombreDescripcion = new javax.swing.JTextField();
        JIFListadoPorPrecio = new javax.swing.JInternalFrame();
        lblListadoPorPrecioTitulo = new javax.swing.JLabel();
        lblListadoPorPrecioEntre = new javax.swing.JLabel();
        txtListadoPorPrecioMin = new javax.swing.JTextField();
        lblListadoPorPrecioY = new javax.swing.JLabel();
        txtListadoPorPrecioMax = new javax.swing.JTextField();
        scpListadoPorPrecio = new javax.swing.JScrollPane();
        tblListadoPorPrecio = new javax.swing.JTable();
        JIFListadoPorRubro = new javax.swing.JInternalFrame();
        lblListadoPorRubroTitulo = new javax.swing.JLabel();
        lblListadoPorRubroRubro = new javax.swing.JLabel();
        cmbListadoPorRubro = new javax.swing.JComboBox<>();
        scpListadoPorRubro = new javax.swing.JScrollPane();
        tblListadoPorRubro = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAdministracion = new javax.swing.JMenu();
        mitGestionDeProductos = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mitConsultaPorNombre = new javax.swing.JMenuItem();
        mitConsultaPorPrecio = new javax.swing.JMenuItem();
        mitConsultaPorRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JIFGestionDeProductos.setVisible(true);
        JIFGestionDeProductos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGestionDeProductosTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblGestionDeProductosTitulo.setText("Gestion de productos");
        JIFGestionDeProductos.getContentPane().add(lblGestionDeProductosTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 0, -1, -1));

        lblGestionDeProductosFiltrar.setText("Filtrar por categoria:");
        JIFGestionDeProductos.getContentPane().add(lblGestionDeProductosFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 49, 168, -1));

        cmbFiltrarPorCategoria.addActionListener(this::cmbFiltrarPorCategoriaActionPerformed);
        JIFGestionDeProductos.getContentPane().add(cmbFiltrarPorCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 44, 300, -1));

        tblGestionDeProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblGestionDeProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGestionDeProductosMouseClicked(evt);
            }
        });
        scpGestionDeProductos.setViewportView(tblGestionDeProductos);

        JIFGestionDeProductos.getContentPane().add(scpGestionDeProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, 592, 98));

        lblGestionDeProductosCodigo.setText("Codigo");

        lblGestionDeProductosDescipcion.setText("Descipcion");

        lblGestionDeProductosPrecio.setText("Precio");

        lblGestionDeProductosRubro.setText("Rubro");

        lblGestionDeProductosStock.setText("Stock");

        txtGestionDeProductosCodigo.setEnabled(false);
        txtGestionDeProductosCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGestionDeProductosCodigoFocusLost(evt);
            }
        });
        txtGestionDeProductosCodigo.addActionListener(this::txtGestionDeProductosCodigoActionPerformed);

        txtGestionDeProductosDescripcion.setEnabled(false);
        txtGestionDeProductosDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGestionDeProductosDescripcionFocusLost(evt);
            }
        });

        txtGestionDeProductosPrecio.setEnabled(false);
        txtGestionDeProductosPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGestionDeProductosPrecioFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGestionDeProductosCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtGestionDeProductosCodigo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGestionDeProductosDescipcion)
                        .addGap(18, 18, 18)
                        .addComponent(txtGestionDeProductosDescripcion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGestionDeProductosPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(txtGestionDeProductosPrecio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGestionDeProductosStock)
                        .addGap(18, 18, 18)
                        .addComponent(spnGestionDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGestionDeProductosRubro)
                        .addGap(18, 18, 18)
                        .addComponent(cmbGestionDeProductosCombo, 0, 313, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosCodigo)
                    .addComponent(txtGestionDeProductosCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosDescipcion)
                    .addComponent(txtGestionDeProductosDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosPrecio)
                    .addComponent(txtGestionDeProductosPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosRubro)
                    .addComponent(cmbGestionDeProductosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosStock)
                    .addComponent(spnGestionDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        JIFGestionDeProductos.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 192, -1, -1));

        btnBuscar.setText("Buscar");
        JIFGestionDeProductos.getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 192, -1, 70));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(this::btnCerrarActionPerformed);
        JIFGestionDeProductos.getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 367, 51, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(this::btnNuevoActionPerformed);
        JIFGestionDeProductos.getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 427, 130, 61));

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        JIFGestionDeProductos.getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 427, 130, 61));

        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        JIFGestionDeProductos.getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 427, 130, 61));

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);
        JIFGestionDeProductos.getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 427, 130, 61));

        JIFListadoPorNombre.setVisible(true);

        lblListadoPorNombreTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblListadoPorNombreTitulo.setText("Listado por nombre");

        lblListadoPorNombreIngDescripcion.setText("Ingrese descripcion:");

        tblListadoPorNombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        scpListadoPorNombre.setViewportView(tblListadoPorNombre);

        javax.swing.GroupLayout JIFListadoPorNombreLayout = new javax.swing.GroupLayout(JIFListadoPorNombre.getContentPane());
        JIFListadoPorNombre.getContentPane().setLayout(JIFListadoPorNombreLayout);
        JIFListadoPorNombreLayout.setHorizontalGroup(
            JIFListadoPorNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JIFListadoPorNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpListadoPorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addGroup(JIFListadoPorNombreLayout.createSequentialGroup()
                        .addGroup(JIFListadoPorNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListadoPorNombreTitulo)
                            .addComponent(lblListadoPorNombreIngDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtListadoPorNombreDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JIFListadoPorNombreLayout.setVerticalGroup(
            JIFListadoPorNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListadoPorNombreTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblListadoPorNombreIngDescripcion)
                .addGap(18, 18, 18)
                .addComponent(txtListadoPorNombreDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(scpListadoPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JIFListadoPorPrecio.setVisible(true);

        lblListadoPorPrecioTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblListadoPorPrecioTitulo.setText("Listado por precio");

        lblListadoPorPrecioEntre.setText("Entre $");

        lblListadoPorPrecioY.setText("Y");

        tblListadoPorPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        scpListadoPorPrecio.setViewportView(tblListadoPorPrecio);

        javax.swing.GroupLayout JIFListadoPorPrecioLayout = new javax.swing.GroupLayout(JIFListadoPorPrecio.getContentPane());
        JIFListadoPorPrecio.getContentPane().setLayout(JIFListadoPorPrecioLayout);
        JIFListadoPorPrecioLayout.setHorizontalGroup(
            JIFListadoPorPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorPrecioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JIFListadoPorPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpListadoPorPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(JIFListadoPorPrecioLayout.createSequentialGroup()
                        .addGroup(JIFListadoPorPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListadoPorPrecioTitulo)
                            .addGroup(JIFListadoPorPrecioLayout.createSequentialGroup()
                                .addComponent(lblListadoPorPrecioEntre)
                                .addGap(18, 18, 18)
                                .addComponent(txtListadoPorPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblListadoPorPrecioY)
                                .addGap(18, 18, 18)
                                .addComponent(txtListadoPorPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JIFListadoPorPrecioLayout.setVerticalGroup(
            JIFListadoPorPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorPrecioLayout.createSequentialGroup()
                .addComponent(lblListadoPorPrecioTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JIFListadoPorPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListadoPorPrecioEntre)
                    .addComponent(txtListadoPorPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListadoPorPrecioY)
                    .addComponent(txtListadoPorPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scpListadoPorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JIFListadoPorRubro.setVisible(true);

        lblListadoPorRubroTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblListadoPorRubroTitulo.setText("Listado por rubro");

        lblListadoPorRubroRubro.setText("Rubro:");

        cmbListadoPorRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblListadoPorRubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        scpListadoPorRubro.setViewportView(tblListadoPorRubro);

        javax.swing.GroupLayout JIFListadoPorRubroLayout = new javax.swing.GroupLayout(JIFListadoPorRubro.getContentPane());
        JIFListadoPorRubro.getContentPane().setLayout(JIFListadoPorRubroLayout);
        JIFListadoPorRubroLayout.setHorizontalGroup(
            JIFListadoPorRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorRubroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JIFListadoPorRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpListadoPorRubro, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(JIFListadoPorRubroLayout.createSequentialGroup()
                        .addGroup(JIFListadoPorRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListadoPorRubroTitulo)
                            .addGroup(JIFListadoPorRubroLayout.createSequentialGroup()
                                .addComponent(lblListadoPorRubroRubro)
                                .addGap(18, 18, 18)
                                .addComponent(cmbListadoPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JIFListadoPorRubroLayout.setVerticalGroup(
            JIFListadoPorRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorRubroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListadoPorRubroTitulo)
                .addGap(18, 18, 18)
                .addGroup(JIFListadoPorRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListadoPorRubroRubro)
                    .addComponent(cmbListadoPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scpListadoPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(JIFGestionDeProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JIFListadoPorNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JIFListadoPorPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JIFListadoPorRubro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(JIFGestionDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JIFListadoPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JIFListadoPorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JIFListadoPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(JIFListadoPorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JIFListadoPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JIFGestionDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JIFListadoPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        mnuAdministracion.setText("Administracion");

        mitGestionDeProductos.setText("Gestion de productos");
        mitGestionDeProductos.addActionListener(this::mitGestionDeProductosActionPerformed);
        mnuAdministracion.add(mitGestionDeProductos);

        jMenuBar1.add(mnuAdministracion);

        mnuConsultas.setText("Consultas");

        mitConsultaPorNombre.setText("Consulta por nombre");
        mitConsultaPorNombre.addActionListener(this::mitConsultaPorNombreActionPerformed);
        mnuConsultas.add(mitConsultaPorNombre);

        mitConsultaPorPrecio.setText("Consulta por precio");
        mitConsultaPorPrecio.addActionListener(this::mitConsultaPorPrecioActionPerformed);
        mnuConsultas.add(mitConsultaPorPrecio);

        mitConsultaPorRubro.setText("Consulta por rubro");
        mitConsultaPorRubro.addActionListener(this::mitConsultaPorRubroActionPerformed);
        mnuConsultas.add(mitConsultaPorRubro);

        jMenuBar1.add(mnuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGestionDeProductosCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGestionDeProductosCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGestionDeProductosCodigoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JIFGestionDeProductos.setVisible(false);
        JIFListadoPorNombre.setVisible(false);
        JIFListadoPorPrecio.setVisible(false);
        JIFListadoPorRubro.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void mitGestionDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitGestionDeProductosActionPerformed
        // TODO add your handling code here:
        JIFGestionDeProductos.setVisible(true);
    }//GEN-LAST:event_mitGestionDeProductosActionPerformed

    private void mitConsultaPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitConsultaPorNombreActionPerformed
        // TODO add your handling code here:
        JIFListadoPorNombre.setVisible(true);
    }//GEN-LAST:event_mitConsultaPorNombreActionPerformed

    private void mitConsultaPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitConsultaPorPrecioActionPerformed
        // TODO add your handling code here:
        JIFListadoPorPrecio.setVisible(true);
    }//GEN-LAST:event_mitConsultaPorPrecioActionPerformed

    private void mitConsultaPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitConsultaPorRubroActionPerformed
        // TODO add your handling code here:
        JIFListadoPorRubro.setVisible(true);
    }//GEN-LAST:event_mitConsultaPorRubroActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
        activarCampos();
        btnActualizar.setEnabled(false);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtGestionDeProductosCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGestionDeProductosCodigoFocusLost
        // TODO add your handling code here:
        String val = "[0-9]*";
        if (!txtGestionDeProductosCodigo.getText().matches(val)) {
            JOptionPane.showMessageDialog(this, "Debe ingresar solo números");
            txtGestionDeProductosCodigo.requestFocus();
        }
    }//GEN-LAST:event_txtGestionDeProductosCodigoFocusLost

    private void txtGestionDeProductosDescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGestionDeProductosDescripcionFocusLost
        // TODO add your handling code here:
        if (txtGestionDeProductosDescripcion.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "La descripcion no debe estar vacia");
            txtGestionDeProductosDescripcion.requestFocus();
        }
    }//GEN-LAST:event_txtGestionDeProductosDescripcionFocusLost

    private void txtGestionDeProductosPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGestionDeProductosPrecioFocusLost
        // TODO add your handling code here:
        try {
            String precio = txtGestionDeProductosPrecio.getText();
            double pre = Double.parseDouble(precio);
        } catch (NumberFormatException nf) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un precio valido");
            txtGestionDeProductosPrecio.requestFocus();
        }
    }//GEN-LAST:event_txtGestionDeProductosPrecioFocusLost

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Producto pro = new Producto();
        pro.setCodigo(Integer.parseInt(txtGestionDeProductosCodigo.getText()));
        pro.setDescripcion(txtGestionDeProductosDescripcion.getText());
        pro.setPrecio(Double.parseDouble(txtGestionDeProductosPrecio.getText()));
        pro.setCategoria((Categoria) cmbGestionDeProductosCombo.getSelectedItem());
        pro.setStock((Integer) spnGestionDeProductos.getValue());

        pd.guardarProducto(pro);
        llenarTabla();
        limpiarCampos();
        desactivarCampos();
        btnGuardar.setEnabled(false);

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtGestionDeProductosCodigo.getText());
        String descripcion = txtGestionDeProductosDescripcion.getText();
        double precio = Double.parseDouble(txtGestionDeProductosPrecio.getText());
        Categoria categoria = (Categoria) cmbFiltrarPorCategoria.getSelectedItem();
        int stock = (Integer) spnGestionDeProductos.getValue();

        productoElegido.setCodigo(codigo);
        productoElegido.setDescripcion(descripcion);
        productoElegido.setPrecio(precio);
        productoElegido.setCategoria(categoria);
        productoElegido.setStock(stock);

        pd.modificarProductor(productoElegido);
        productoElegido = null;
        limpiarCampos();
        desactivarCampos();
        llenarTabla();
        btnActualizar.setEnabled(false);

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cmbFiltrarPorCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltrarPorCategoriaActionPerformed
        // TODO add your handling code here:
        llenarTabla();
    }//GEN-LAST:event_cmbFiltrarPorCategoriaActionPerformed

    private void tblGestionDeProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGestionDeProductosMouseClicked
        // TODO add your handling code here:
        btnActualizar.setEnabled(true);
        btnEliminar.setEnabled(true);
        int filaElegida = tblGestionDeProductos.getSelectedRow();

        if (filaElegida != -1) {
            int idProducto = (Integer) tblGestionDeProductos.getValueAt(filaElegida, 0);
            int codigo = (Integer) tblGestionDeProductos.getValueAt(filaElegida, 1);
            String descripcion = (String) tblGestionDeProductos.getValueAt(filaElegida, 2);
            double precio = (Double) tblGestionDeProductos.getValueAt(filaElegida, 3);
            Categoria tablaCate = (Categoria) tblGestionDeProductos.getValueAt(filaElegida, 4);
            int stock = (Integer) tblGestionDeProductos.getValueAt(filaElegida, 5);

            txtGestionDeProductosCodigo.setText(codigo + "");
            txtGestionDeProductosDescripcion.setText(descripcion);
            txtGestionDeProductosPrecio.setText(precio + "");
            cmbGestionDeProductosCombo.setSelectedItem(tablaCate);
            spnGestionDeProductos.setValue(stock);

            activarCampos();
            productoElegido = new Producto();
            productoElegido.setIdProducto(idProducto);
            productoElegido.setCodigo(codigo);
            productoElegido.setDescripcion(descripcion);
            productoElegido.setPrecio(precio);
            productoElegido.setCategoria(tablaCate);
            productoElegido.setStock(stock);

        }
    }//GEN-LAST:event_tblGestionDeProductosMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        pd.borrarProducto(productoElegido);
        llenarTabla();
        limpiarCampos();
        desactivarCampos();
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Escritorio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame JIFGestionDeProductos;
    private javax.swing.JInternalFrame JIFListadoPorNombre;
    private javax.swing.JInternalFrame JIFListadoPorPrecio;
    private javax.swing.JInternalFrame JIFListadoPorRubro;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<Categoria> cmbFiltrarPorCategoria;
    private javax.swing.JComboBox<Categoria> cmbGestionDeProductosCombo;
    private javax.swing.JComboBox<String> cmbListadoPorRubro;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGestionDeProductosCodigo;
    private javax.swing.JLabel lblGestionDeProductosDescipcion;
    private javax.swing.JLabel lblGestionDeProductosFiltrar;
    private javax.swing.JLabel lblGestionDeProductosPrecio;
    private javax.swing.JLabel lblGestionDeProductosRubro;
    private javax.swing.JLabel lblGestionDeProductosStock;
    private javax.swing.JLabel lblGestionDeProductosTitulo;
    private javax.swing.JLabel lblListadoPorNombreIngDescripcion;
    private javax.swing.JLabel lblListadoPorNombreTitulo;
    private javax.swing.JLabel lblListadoPorPrecioEntre;
    private javax.swing.JLabel lblListadoPorPrecioTitulo;
    private javax.swing.JLabel lblListadoPorPrecioY;
    private javax.swing.JLabel lblListadoPorRubroRubro;
    private javax.swing.JLabel lblListadoPorRubroTitulo;
    private javax.swing.JMenuItem mitConsultaPorNombre;
    private javax.swing.JMenuItem mitConsultaPorPrecio;
    private javax.swing.JMenuItem mitConsultaPorRubro;
    private javax.swing.JMenuItem mitGestionDeProductos;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JScrollPane scpGestionDeProductos;
    private javax.swing.JScrollPane scpListadoPorNombre;
    private javax.swing.JScrollPane scpListadoPorPrecio;
    private javax.swing.JScrollPane scpListadoPorRubro;
    private javax.swing.JSpinner spnGestionDeProductos;
    private javax.swing.JTable tblGestionDeProductos;
    private javax.swing.JTable tblListadoPorNombre;
    private javax.swing.JTable tblListadoPorPrecio;
    private javax.swing.JTable tblListadoPorRubro;
    private javax.swing.JTextField txtGestionDeProductosCodigo;
    private javax.swing.JTextField txtGestionDeProductosDescripcion;
    private javax.swing.JTextField txtGestionDeProductosPrecio;
    private javax.swing.JTextField txtListadoPorNombreDescripcion;
    private javax.swing.JTextField txtListadoPorPrecioMax;
    private javax.swing.JTextField txtListadoPorPrecioMin;
    // End of variables declaration//GEN-END:variables
    private void llenarCM() {
        for (Categoria l : cd.obtenerCategoria()) {
            cmbFiltrarPorCategoria.addItem(l);
            cmbGestionDeProductosCombo.addItem(l);

            cmbFiltrarPorCategoria.setSelectedIndex(-1);
        }
    }

    private void activarCampos() {
        txtGestionDeProductosCodigo.setEnabled(true);
        txtGestionDeProductosDescripcion.setEnabled(true);
        txtGestionDeProductosPrecio.setEnabled(true);
        spnGestionDeProductos.setEnabled(true);
        cmbGestionDeProductosCombo.setEnabled(true);
    }

    private void desactivarCampos() {
        txtGestionDeProductosCodigo.setEnabled(false);
        txtGestionDeProductosDescripcion.setEnabled(false);
        txtGestionDeProductosPrecio.setEnabled(false);
        spnGestionDeProductos.setEnabled(false);
        cmbGestionDeProductosCombo.setEnabled(false);
    }

    private void limpiarCampos() {
        txtGestionDeProductosCodigo.setText("");
        txtGestionDeProductosDescripcion.setText("");
        txtGestionDeProductosPrecio.setText("");
        cmbGestionDeProductosCombo.setSelectedIndex(-1);
        spnGestionDeProductos.setValue(0);
    }

    private void llenarCabezera() {
        ArrayList<Object> c = new ArrayList<>();
        c.add("ID");
        c.add("Codigo");
        c.add("Descripcion");
        c.add("Precio");
        c.add("Categoria");
        c.add("Stock");

        for (Object it : c) {
            modelo.addColumn(it);
            tblGestionDeProductos.setModel(modelo);

        }
    }

    private void llenarTabla() {

        borrarFila();
        Categoria sel = (Categoria) cmbFiltrarPorCategoria.getSelectedItem();

        if (sel != null) {
            for (Producto p : pd.obtenerProducto()) {

                if (p.getCategoria().equals(sel)) {

                    modelo.addRow(new Object[]{p.getIdProducto(), p.getCodigo(), p.getDescripcion(), p.getPrecio(), p.getCategoria(), p.getStock()});
                }
            }
        }
    }

    private void borrarFila() {
        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

}
