/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author FEDE-PC
 */
public class Escritorio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Escritorio.class.getName());

    /**
     * Creates new form Escritorio
     */
    public Escritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        JIFGestionDeProductos = new javax.swing.JInternalFrame();
        lblGestionDeProductosTitulo = new javax.swing.JLabel();
        lblGestionDeProductosFiltrar = new javax.swing.JLabel();
        cmbFiltrarPorCategoria = new javax.swing.JComboBox<>();
        scpGestionDeProductos = new javax.swing.JScrollPane();
        tblGestionDeProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblGestionDeProductosCodigo = new javax.swing.JLabel();
        lblGestionDeProductosDescipcion = new javax.swing.JLabel();
        lblGestionDeProductosPrecio = new javax.swing.JLabel();
        lblGestionDeProductosRubro = new javax.swing.JLabel();
        lblGestionDeProductosStock = new javax.swing.JLabel();
        txtGestionDeProductosCodigo = new javax.swing.JTextField();
        txtGestionDeProductosDescripcion = new javax.swing.JTextField();
        txtGestionDeProductosPrecio = new javax.swing.JTextField();
        cmbGestionDeProductosCombo = new javax.swing.JComboBox<>();
        spnGestionDeProductos = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        JIFListadoPorNombre = new javax.swing.JInternalFrame();
        lblListadoPorNombreTitulo = new javax.swing.JLabel();
        lblListadoPorNombreIngDescripcion = new javax.swing.JLabel();
        scpListadoPorNombre = new javax.swing.JScrollPane();
        tblListadoPorNombre = new javax.swing.JTable();
        txtListadoPorNombreDescripcion = new javax.swing.JTextField();
        JIFListadoPorPrecio = new javax.swing.JInternalFrame();
        lblListadoPorPrecioTitulo = new javax.swing.JLabel();
        lblListadoPorPrecioEntre = new javax.swing.JLabel();
        txtListadoPorPrecioMin = new javax.swing.JTextField();
        lblListadoPorPrecioY = new javax.swing.JLabel();
        txtListadoPorPrecioMax = new javax.swing.JTextField();
        scpListadoPorPrecio = new javax.swing.JScrollPane();
        tblListadoPorPrecio = new javax.swing.JTable();
        JIFListadoPorRubro = new javax.swing.JInternalFrame();
        lblListadoPorRubroTitulo = new javax.swing.JLabel();
        lblListadoPorRubroRubro = new javax.swing.JLabel();
        cmbListadoPorRubro = new javax.swing.JComboBox<>();
        scpListadoPorRubro = new javax.swing.JScrollPane();
        tblListadoPorRubro = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAdministracion = new javax.swing.JMenu();
        mitGestionDeProductos = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mitConsultaPorNombre = new javax.swing.JMenuItem();
        mitConsultaPorPrecio = new javax.swing.JMenuItem();
        mitConsultaPorRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JIFGestionDeProductos.setVisible(true);

        lblGestionDeProductosTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblGestionDeProductosTitulo.setText("Gestion de productos");

        lblGestionDeProductosFiltrar.setText("Filtrar por categoria:");

        cmbFiltrarPorCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblGestionDeProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        scpGestionDeProductos.setViewportView(tblGestionDeProductos);

        lblGestionDeProductosCodigo.setText("Codigo");

        lblGestionDeProductosDescipcion.setText("Descipcion");

        lblGestionDeProductosPrecio.setText("Precio");

        lblGestionDeProductosRubro.setText("Rubro");

        lblGestionDeProductosStock.setText("Stock");

        txtGestionDeProductosCodigo.addActionListener(this::txtGestionDeProductosCodigoActionPerformed);

        cmbGestionDeProductosCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGestionDeProductosCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtGestionDeProductosCodigo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGestionDeProductosDescipcion)
                        .addGap(18, 18, 18)
                        .addComponent(txtGestionDeProductosDescripcion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGestionDeProductosPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(txtGestionDeProductosPrecio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGestionDeProductosStock)
                        .addGap(18, 18, 18)
                        .addComponent(spnGestionDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGestionDeProductosRubro)
                        .addGap(18, 18, 18)
                        .addComponent(cmbGestionDeProductosCombo, 0, 313, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosCodigo)
                    .addComponent(txtGestionDeProductosCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosDescipcion)
                    .addComponent(txtGestionDeProductosDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosPrecio)
                    .addComponent(txtGestionDeProductosPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosRubro)
                    .addComponent(cmbGestionDeProductosCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosStock)
                    .addComponent(spnGestionDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnBuscar.setText("Buscar");

        btnCerrar.setText("Cerrar");

        btnNuevo.setText("Nuevo");

        btnGuardar.setText("Guardar");

        btnActualizar.setText("Actualizar");

        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout JIFGestionDeProductosLayout = new javax.swing.GroupLayout(JIFGestionDeProductos.getContentPane());
        JIFGestionDeProductos.getContentPane().setLayout(JIFGestionDeProductosLayout);
        JIFGestionDeProductosLayout.setHorizontalGroup(
            JIFGestionDeProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JIFGestionDeProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGestionDeProductosTitulo)
                .addGap(198, 198, 198))
            .addGroup(JIFGestionDeProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpGestionDeProductos)
                .addContainerGap())
            .addGroup(JIFGestionDeProductosLayout.createSequentialGroup()
                .addGroup(JIFGestionDeProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JIFGestionDeProductosLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblGestionDeProductosFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFiltrarPorCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JIFGestionDeProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(JIFGestionDeProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(JIFGestionDeProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        JIFGestionDeProductosLayout.setVerticalGroup(
            JIFGestionDeProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JIFGestionDeProductosLayout.createSequentialGroup()
                .addComponent(lblGestionDeProductosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JIFGestionDeProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGestionDeProductosFiltrar)
                    .addComponent(cmbFiltrarPorCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scpGestionDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JIFGestionDeProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JIFGestionDeProductosLayout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(btnCerrar)))
                .addGap(18, 18, 18)
                .addGroup(JIFGestionDeProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        JIFListadoPorNombre.setVisible(true);

        lblListadoPorNombreTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblListadoPorNombreTitulo.setText("Listado por nombre");

        lblListadoPorNombreIngDescripcion.setText("Ingrese descripcion:");

        tblListadoPorNombre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        scpListadoPorNombre.setViewportView(tblListadoPorNombre);

        javax.swing.GroupLayout JIFListadoPorNombreLayout = new javax.swing.GroupLayout(JIFListadoPorNombre.getContentPane());
        JIFListadoPorNombre.getContentPane().setLayout(JIFListadoPorNombreLayout);
        JIFListadoPorNombreLayout.setHorizontalGroup(
            JIFListadoPorNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JIFListadoPorNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpListadoPorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                    .addGroup(JIFListadoPorNombreLayout.createSequentialGroup()
                        .addGroup(JIFListadoPorNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListadoPorNombreTitulo)
                            .addComponent(lblListadoPorNombreIngDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtListadoPorNombreDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JIFListadoPorNombreLayout.setVerticalGroup(
            JIFListadoPorNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListadoPorNombreTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblListadoPorNombreIngDescripcion)
                .addGap(18, 18, 18)
                .addComponent(txtListadoPorNombreDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(scpListadoPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JIFListadoPorPrecio.setVisible(true);

        lblListadoPorPrecioTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblListadoPorPrecioTitulo.setText("Listado por precio");

        lblListadoPorPrecioEntre.setText("Entre $");

        lblListadoPorPrecioY.setText("Y");

        tblListadoPorPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        scpListadoPorPrecio.setViewportView(tblListadoPorPrecio);

        javax.swing.GroupLayout JIFListadoPorPrecioLayout = new javax.swing.GroupLayout(JIFListadoPorPrecio.getContentPane());
        JIFListadoPorPrecio.getContentPane().setLayout(JIFListadoPorPrecioLayout);
        JIFListadoPorPrecioLayout.setHorizontalGroup(
            JIFListadoPorPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorPrecioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JIFListadoPorPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpListadoPorPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(JIFListadoPorPrecioLayout.createSequentialGroup()
                        .addGroup(JIFListadoPorPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListadoPorPrecioTitulo)
                            .addGroup(JIFListadoPorPrecioLayout.createSequentialGroup()
                                .addComponent(lblListadoPorPrecioEntre)
                                .addGap(18, 18, 18)
                                .addComponent(txtListadoPorPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblListadoPorPrecioY)
                                .addGap(18, 18, 18)
                                .addComponent(txtListadoPorPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JIFListadoPorPrecioLayout.setVerticalGroup(
            JIFListadoPorPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorPrecioLayout.createSequentialGroup()
                .addComponent(lblListadoPorPrecioTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JIFListadoPorPrecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListadoPorPrecioEntre)
                    .addComponent(txtListadoPorPrecioMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblListadoPorPrecioY)
                    .addComponent(txtListadoPorPrecioMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scpListadoPorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JIFListadoPorRubro.setVisible(true);

        lblListadoPorRubroTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblListadoPorRubroTitulo.setText("Listado por rubro");

        lblListadoPorRubroRubro.setText("Rubro:");

        cmbListadoPorRubro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblListadoPorRubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        scpListadoPorRubro.setViewportView(tblListadoPorRubro);

        javax.swing.GroupLayout JIFListadoPorRubroLayout = new javax.swing.GroupLayout(JIFListadoPorRubro.getContentPane());
        JIFListadoPorRubro.getContentPane().setLayout(JIFListadoPorRubroLayout);
        JIFListadoPorRubroLayout.setHorizontalGroup(
            JIFListadoPorRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorRubroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JIFListadoPorRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpListadoPorRubro, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(JIFListadoPorRubroLayout.createSequentialGroup()
                        .addGroup(JIFListadoPorRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListadoPorRubroTitulo)
                            .addGroup(JIFListadoPorRubroLayout.createSequentialGroup()
                                .addComponent(lblListadoPorRubroRubro)
                                .addGap(18, 18, 18)
                                .addComponent(cmbListadoPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        JIFListadoPorRubroLayout.setVerticalGroup(
            JIFListadoPorRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JIFListadoPorRubroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblListadoPorRubroTitulo)
                .addGap(18, 18, 18)
                .addGroup(JIFListadoPorRubroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListadoPorRubroRubro)
                    .addComponent(cmbListadoPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scpListadoPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(JIFGestionDeProductos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JIFListadoPorNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JIFListadoPorPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JIFListadoPorRubro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JIFGestionDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(357, Short.MAX_VALUE)
                    .addComponent(JIFListadoPorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(357, Short.MAX_VALUE)
                    .addComponent(JIFListadoPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addComponent(JIFListadoPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 358, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(234, Short.MAX_VALUE)
                    .addComponent(JIFGestionDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JIFListadoPorPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(234, Short.MAX_VALUE)
                    .addComponent(JIFListadoPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(JIFListadoPorRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        mnuAdministracion.setText("Administracion");

        mitGestionDeProductos.setText("Gestion de productos");
        mitGestionDeProductos.addActionListener(this::mitGestionDeProductosActionPerformed);
        mnuAdministracion.add(mitGestionDeProductos);

        jMenuBar1.add(mnuAdministracion);

        mnuConsultas.setText("Consultas");

        mitConsultaPorNombre.setText("Consulta por nombre");
        mitConsultaPorNombre.addActionListener(this::mitConsultaPorNombreActionPerformed);
        mnuConsultas.add(mitConsultaPorNombre);

        mitConsultaPorPrecio.setText("Consulta por precio");
        mitConsultaPorPrecio.addActionListener(this::mitConsultaPorPrecioActionPerformed);
        mnuConsultas.add(mitConsultaPorPrecio);

        mitConsultaPorRubro.setText("Consulta por rubro");
        mitConsultaPorRubro.addActionListener(this::mitConsultaPorRubroActionPerformed);
        mnuConsultas.add(mitConsultaPorRubro);

        jMenuBar1.add(mnuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGestionDeProductosCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGestionDeProductosCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGestionDeProductosCodigoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JIFGestionDeProductos.setVisible(false);
        JIFListadoPorNombre.setVisible(false);
        JIFListadoPorPrecio.setVisible(false);
        JIFListadoPorRubro.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void mitGestionDeProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitGestionDeProductosActionPerformed
        // TODO add your handling code here:
        JIFGestionDeProductos.setVisible(true);
    }//GEN-LAST:event_mitGestionDeProductosActionPerformed

    private void mitConsultaPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitConsultaPorNombreActionPerformed
        // TODO add your handling code here:
        JIFListadoPorNombre.setVisible(true);
    }//GEN-LAST:event_mitConsultaPorNombreActionPerformed

    private void mitConsultaPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitConsultaPorPrecioActionPerformed
        // TODO add your handling code here:
        JIFListadoPorPrecio.setVisible(true);
    }//GEN-LAST:event_mitConsultaPorPrecioActionPerformed

    private void mitConsultaPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitConsultaPorRubroActionPerformed
        // TODO add your handling code here:
        JIFListadoPorRubro.setVisible(true);
    }//GEN-LAST:event_mitConsultaPorRubroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Escritorio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame JIFGestionDeProductos;
    private javax.swing.JInternalFrame JIFListadoPorNombre;
    private javax.swing.JInternalFrame JIFListadoPorPrecio;
    private javax.swing.JInternalFrame JIFListadoPorRubro;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbFiltrarPorCategoria;
    private javax.swing.JComboBox<String> cmbGestionDeProductosCombo;
    private javax.swing.JComboBox<String> cmbListadoPorRubro;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblGestionDeProductosCodigo;
    private javax.swing.JLabel lblGestionDeProductosDescipcion;
    private javax.swing.JLabel lblGestionDeProductosFiltrar;
    private javax.swing.JLabel lblGestionDeProductosPrecio;
    private javax.swing.JLabel lblGestionDeProductosRubro;
    private javax.swing.JLabel lblGestionDeProductosStock;
    private javax.swing.JLabel lblGestionDeProductosTitulo;
    private javax.swing.JLabel lblListadoPorNombreIngDescripcion;
    private javax.swing.JLabel lblListadoPorNombreTitulo;
    private javax.swing.JLabel lblListadoPorPrecioEntre;
    private javax.swing.JLabel lblListadoPorPrecioTitulo;
    private javax.swing.JLabel lblListadoPorPrecioY;
    private javax.swing.JLabel lblListadoPorRubroRubro;
    private javax.swing.JLabel lblListadoPorRubroTitulo;
    private javax.swing.JMenuItem mitConsultaPorNombre;
    private javax.swing.JMenuItem mitConsultaPorPrecio;
    private javax.swing.JMenuItem mitConsultaPorRubro;
    private javax.swing.JMenuItem mitGestionDeProductos;
    private javax.swing.JMenu mnuAdministracion;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JScrollPane scpGestionDeProductos;
    private javax.swing.JScrollPane scpListadoPorNombre;
    private javax.swing.JScrollPane scpListadoPorPrecio;
    private javax.swing.JScrollPane scpListadoPorRubro;
    private javax.swing.JSpinner spnGestionDeProductos;
    private javax.swing.JTable tblGestionDeProductos;
    private javax.swing.JTable tblListadoPorNombre;
    private javax.swing.JTable tblListadoPorPrecio;
    private javax.swing.JTable tblListadoPorRubro;
    private javax.swing.JTextField txtGestionDeProductosCodigo;
    private javax.swing.JTextField txtGestionDeProductosDescripcion;
    private javax.swing.JTextField txtGestionDeProductosPrecio;
    private javax.swing.JTextField txtListadoPorNombreDescripcion;
    private javax.swing.JTextField txtListadoPorPrecioMax;
    private javax.swing.JTextField txtListadoPorPrecioMin;
    // End of variables declaration//GEN-END:variables
}
